version: '3.8'

services:
  mysql:
    image: mysql:8.0
    platform: linux/arm64
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DATABASENAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  app:
    build: .
    platform: linux/arm64
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: ${USER}
      DB_PASSWORD: ${PASSWORD}
      DB_NAME: ${DATABASENAME}

volumes:
  mysql-data:
